{% set name = "opentelemetry-instrumentation-aiopg" %}
{% set version = "0.36b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_aiopg-{{ version }}.tar.gz
  sha256: f144ecdd35b2a7185d1f4338368ff77f91dc634fde4a139dbf57ef950fb669ee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api >=1.12,<2.dev0
    - opentelemetry-instrumentation-dbapi ==0.36b0
    - opentelemetry-instrumentation ==0.36b0
    - wrapt <2.0.0,>=1.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-aiopg
  summary: OpenTelemetry aiopg instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
