{% set name = "opentelemetry-instrumentation-aiopg" %}
{% set version = "0.25b2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-aiopg-{{ version }}.tar.gz
  sha256: f695b3642813e46e42cc06b0f9c655aef7c80d0549c00d0289ef8ea4e4255ecb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.25b2
    - opentelemetry-instrumentation-dbapi ==0.25b2
    - opentelemetry-semantic-conventions ==0.25b2
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - opentelemetry-test ==0.24b0
    # - aiopg <1.3.0,>=0.13.0
    # - opentelemetry-test ==0.25b0
    # - aiopg <1.3.0,>=0.13.0
    # - opentelemetry-test ==0.25b2
    # - aiopg <1.3.0,>=0.13.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-aiopg
  summary: OpenTelemetry aiopg instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
